### ISSUE TITLE
sauvegarde des aria-describedby déjà présents sur le lien

### ISSUE THREAD

**Issue by jum44** [nico3333fr/jquery-accessible-simple-tooltip-aria#11]
Je suis dans un cas où j'ai besoin de définir un aria-describedby sur le lien ouvrant la tooltip, mais le script actuel, lors de la création de la tootltip, supprime le aria-describedby existant, je perd donc une information.

J'ai tenté un bout de code pour ajouter avant l'aria-describedby généré, celui existant, mais la tooltip ne s'affiche plus.

Merci d'avance :)

**Comment by nico3333fr** [comment]
Hello,

le fix est publié, merci beaucoup pour cette idée 👍 

Au plaisir,
Nico
