### ISSUE TITLE
Publish as npm package

### ISSUE THREAD

**Issue by ffoodd** [nico3333fr/jquery-accessible-simple-tooltip-aria#4]
See the « [publishing npm package](https://docs.npmjs.com/getting-started/publishing-npm-packages) » documentation.

**Comment by tzi** [comment]
+1
Ce n'est pas très difficile, et c'est très pratique.
Les projets fronts se font de plus en plus avec npm depuis la démocratisation des outils tel que gulp ou grunt.

Par contre, une contrainte est de versionner le code avec des tags ;)

**Comment by nico3333fr** [comment]
Yop, c'était le dernier de la liste http://a11y.nicolas-hoffmann.net/ , mais ça sera sûrement pas le dernier à y aller. ;) https://www.npmjs.com/package/jquery-accessible-simple-tooltip-aria
