### ISSUE TITLE
Demos aren't compatible with IE 8, but plugins are

### ISSUE THREAD

**Issue by samrichca** [nico3333fr/jquery-accessible-simple-tooltip-aria#9]
Hi, I appreciate your work on all these accessible plugins! However I had trouble figuring out if your plugins fit my needs. The demos are not compatible with IE 8. The plugins work well when I put them in my site though. I have a couple of suggestions for improving the demos:

* Change jQuery link to script src="**//**code.jquery..." because IE blocks **http://**code.jquery...
* Use fallbacks for RGBA, e.g. a hex colour code.

Thanks!

**Comment by nico3333fr** [comment]
Yes, you're right, I've updated this demo. :)
